### ISSUE TITLE
Doesn't understand all log paths that the log module might use

### ISSUE THREAD

**Issue by dgw** [jdarmst/znc-modules#1]
The ZNC log module supports placeholders like %Y, %m, and %d in addition to the documented $USER, $NETWORK, and $WINDOW substitutions. However, znc-backlog does not. This makes znc-backlog unusable with ZNC installations that log to directories using these placeholders.

**Comment by jdarmst** [comment]
could you please elaborate on this? My modules haven't done anything with logging >.>

**Comment by dgw** [comment]
It's not possible for me to use znc-backlog with the log module set up the way I have it. It logs to `%Y/%m/%d/$NETWORK_$WINDOW.log` but specifying that pattern in this module means I get "Could not list directory %Y/%m/%d: No such file or directory" on requesting backlog.

**Comment by dgw** [comment]
Resubmitted in the proper place: FruitieX/znc-backlog#3

Closing. Sorry for the bother, @jdarmst. I still have no idea how this issue ended up in your repo.
